# Docker Compose configuration for BOB Camera with WebGUI
version: '3.8'

services:
  # Backend service (placeholder - replace with actual backend service)
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config
    networks:
      - bob-network

  # Web UI service
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - ENABLE_UI=${ENABLE_UI:-true}
    profiles: ["ui"]
    networks:
      - bob-network

networks:
  bob-network:
    driver: bridge

volumes:
  bob-data: